feat: support for stylelint 14 and added missing rules
hivesolutions/stylelint_config_hive pull request #3
Opened 2021-12-01 16:21 UTC by BeeMargarida

* `Stylelint v14` droped automatic inferral of syntax and no longer includes syntax for SCSS and does not extract styles from HTML and others: https://stylelint.io/migration-guide/to-14/
   * This requires the use of a config for vue `stylelint-config-html/vue` (requires stylelint-config-html and postcss-html) and for scss `stylelint-config-standard-scss`
* `stylelint-config-standard` added new rules in `v23` that are against the standards used: https://github.com/stylelint/stylelint-config-standard/releases

2021-12-01 16:22 UTC, BeeMargarida commented
@joamag There were some missing changes needed for working with stylelint v14, which added several breaking changes.

2021-12-01 19:12 UTC, joamag requested changes

2021-12-01 19:12 UTC, joamag commented on index.js
> +        "shorthand-property-no-redundant-values": null,
I think the key are sorted alphabetically :)

2021-12-01 19:13 UTC, joamag commented
@BeeMargarida It's critical to avoid changes to the current way of styling CSS and SCSS so every time we find something breaking the consistency let's try to find alternatives

2021-12-02 09:34 UTC, BeeMargarida commented
> @BeeMargarida It's critical to avoid changes to the current way of styling CSS and SCSS so every time we find something breaking the consistency let's try to find alternatives

@joamag These changes are required so that the way of styling CSS and SCSS does not change in our current projects using stylelint v14. The only thing that needed change (in ripe-white, for example), was the way we import/declare font names: https://github.com/ripe-tech/ripe-white/pull/936/commits/562c1c303c32f3572e077ab5b82fb21a88d39cae
We were using `url` with and without `"`, which is not allowed by the rules [`function-url-quotes`](https://github.com/stylelint/stylelint/blob/main/lib/rules/function-url-quotes/README.md) and [`font-family-name-quotes`](https://github.com/stylelint/stylelint/blob/main/lib/rules/font-family-name-quotes/README.md).

I also tested in another repo (pulse) and only two changes are needed (which do not follow the standards - use of `'` instead of `"` and use `pascalCase` instead of `kebab-case` in CSS classes.

2021-12-02 12:43 UTC, joamag approved these changes

2021-12-02 12:43 UTC, merged

2021-12-02 12:51 UTC, BeeMargarida commented
@joamag Would it be possible to create a new version with these changes?